# Generated by Django 5.1.1 on 2025-01-17 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="يرجى تحميل صورة للشعار.",
                        upload_to="images/logos/",
                        verbose_name="صورة الشعار",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال وصف اختياري للشعار.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="وصف الشعار",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="تاريخ إنشاء الشعار."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="تاريخ آخر تحديث للشعار."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التحديث بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "شعار",
                "verbose_name_plural": "شعارات",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogoChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل"),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="core.logo",
                        verbose_name="الشعار",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغيير الشعار",
                "verbose_name_plural": "سجلات تغيير الشعار",
            },
        ),
        migrations.CreateModel(
            name="Main_About_US",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="يرجى    ادخال عبارة تعبر عن عنوان للتواصل .",
                        max_length=100,
                        unique=True,
                        verbose_name="عنوان الاتصال بنا",
                    ),
                ),
                (
                    "massage",
                    models.CharField(
                        blank=True,
                        help_text="يرجى الرسالة او  النص  المكتوب في الاتصال بنا.",
                        max_length=1000,
                        null=True,
                        verbose_name=" النص المكتوب في الاتصال بنا  ",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="يرجى ادخال رقم هاتف للتواصل",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف 11 رقماً فقط.",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="عنوان البريد الإلكتروني  للمركز.",
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="أدخل عنوان بريد إلكتروني صحيح."
                            )
                        ],
                    ),
                ),
                (
                    "locations",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال موقع المركز  .",
                        max_length=100,
                        null=True,
                        verbose_name="موقع المركز   ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للاسم الشهادة (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات  .",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="main_about_uS_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "الاتصال بنا    ",
                "verbose_name_plural": "الاتصال بنا ",
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "can_create_main_about_us",
                        " يمكن إنشاء نموذج الاتصال بنا وتغير الشعار",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeMain_About_USLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="اسم الحقل"),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم التغيير بواسطة",
                    ),
                ),
                (
                    "main_about_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="core.main_about_us",
                        verbose_name="السجل المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل التغيير",
                "verbose_name_plural": "سجلات التغيير",
            },
        ),
    ]
