# Generated by Django 5.1.1 on 2025-01-17 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hrhub", "0001_initial"),
        ("locations", "0001_initial"),
        ("personalinfo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="الرجاء ادخل اسم الكلية باللغة العربية.",
                        max_length=255,
                        unique=True,
                        verbose_name="اسم الكلية باللغة العربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        help_text="الرجاء ادخل اسم الكلية باللغة الانكليزية.",
                        max_length=255,
                        unique=True,
                        verbose_name="اسم الكلية باللغة الانكليزية",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slug for the college, auto-generated if left blank.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموظف الذي قام بإنشاء هذه المعلومات الخاصة الكلية.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="college_employment_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="College ",
                    ),
                ),
            ],
            options={
                "verbose_name": "الكلية",
                "verbose_name_plural": "الكليات",
                "ordering": ["name_in_english"],
                "permissions": [
                    ("can_add_college", "يمكن اضافة اسم الكلية"),
                    ("can_update_college", "يمكن تحديث اسم الكلية    "),
                    ("can_delete_college", "يمكن حذف اسم   الكلية "),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollegeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.college",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الكلية",
                "verbose_name_plural": "سجلات تغييرات الكليات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CourseCertificateInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم الشهادة بالعربية.",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الشهادة  بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم الشهادة بالانكليزية.",
                        max_length=50,
                        null=True,
                        verbose_name="اسم الشهادة  بالانكليزية",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات "),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="تاريخ ووقت إنشاء السجل.",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="تاريخ ووقت آخر تحديث للسجل.",
                        verbose_name="تاريخ التحديث",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالمدرسة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_certificate_institution_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مؤسسة شهادة الدورة",
                "verbose_name_plural": "مؤسسات شهادات الدورات",
                "ordering": ["name_in_arabic"],
                "permissions": [
                    (
                        "can_add_course_certificate_institution",
                        "يمكن إضافة مؤسسة شهادة دورة",
                    ),
                    (
                        "can_update_course_certificate_institution",
                        "يمكن تحديث مؤسسة شهادة دورة",
                    ),
                    (
                        "can_delete_course_certificate_institution",
                        "يمكن حذف مؤسسة شهادة دورة",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseCertificateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم الشهادة بالعربية.",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الشهادة  بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم الشهادة بالانكليزية.",
                        max_length=50,
                        null=True,
                        verbose_name="اسم الشهادة  بالانكليزية",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="هل يوجد لها تاثير على الامور الادارية مثل الترفع  ",
                        verbose_name="هل هي مطلوبة للاغراض الادارية    ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="تاريخ ووقت إنشاء السجل.",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="تاريخ ووقت آخر تحديث للسجل.",
                        verbose_name="تاريخ التحديث",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالمدرسة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_certificate_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع شهادة الدورة",
                "verbose_name_plural": "أنواع شهادات الدورات",
                "ordering": ["name_in_arabic"],
                "permissions": [
                    ("can_add_course_certificate_type", "يمكن إضافة نوع شهادة الدورة"),
                    (
                        "can_update_course_certificate_type",
                        "يمكن تحديث نوع شهادة الدورة",
                    ),
                    ("can_delete_course_certificate_type", "يمكن حذف نوع شهادة الدورة"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseCertificateTypeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "course_certificate_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.coursecertificatetype",
                        verbose_name="نوع شهادة الدورة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات نوع شهادة الدورة",
                "verbose_name_plural": "سجلات تغييرات أنواع شهادات الدورات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EducationDegreeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم الشهادة بالعربية.",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الشهادة العلمية بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم الشهادة بالانكليزية.",
                        max_length=50,
                        null=True,
                        verbose_name="اسم الشهادة العلمية بالانكليزية",
                    ),
                ),
                (
                    "education_degree_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="يرجى إدخال مستوى الشهادة. هذا الحقل مفيد لغرض احتساب الشهادة المضافة - يبدأ هذا الحقل تصاعديًا من 1 فما فوق.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="رقم مستوى الشهادة يجب أن يكون 1 أو أعلى"
                            )
                        ],
                        verbose_name="مستوى الشهادة",
                    ),
                ),
                (
                    "years_effects",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="ادخال تاثير هذا النوع على عدد سنوات الترفيع في الحالات الطبيعية بدون اضافة شهادة",
                        null=True,
                        verbose_name=" سنوات الترفيع ",
                    ),
                ),
                (
                    "stop_point",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="ادخل الدرجة الوظيفية التي يتوقف عندها صاحب الشهادة ",
                        null=True,
                    ),
                ),
                (
                    "has_effect",
                    models.BooleanField(
                        default=False,
                        help_text="تحديد ما إذا كان لهذا النوع من الشهادات تأثير على الدرجة  الوظيفية وسنوات الترفيع في حالة الشهادات المضافة .",
                        verbose_name="تاثيره في الشهادات المضافة ",
                    ),
                ),
                (
                    "addtion_years_effects",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="ادخال تاثير الشهادة المضافة من هذا النوع على عدد السنوات",
                        null=True,
                        verbose_name=" سنوات التسريع في حال الشهادة المضافة   ",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="ملاحظات عن الشهادة الدراسية او الاكاديمية",
                        max_length=250,
                        null=True,
                        verbose_name="ملاحظات عن الشهادة الدراسية او الاكاديمية",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للاسم الشهادة (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالمدرسة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="education_degree_type_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade_number",
                    models.ForeignKey(
                        blank=True,
                        help_text="الدرجة الوظيفية المرتبطة بهذه الشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="education_degrees",
                        to="hrhub.employeegrade",
                        verbose_name="الدرجة الوظيفية",
                    ),
                ),
                (
                    "step_number",
                    models.ForeignKey(
                        blank=True,
                        help_text="المرحلة الوظيفية المرتبطة بهذه الشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="education_degrees",
                        to="hrhub.employeestep",
                        verbose_name="المرحلة الوظيفية",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع الشهادة الدراسية ",
                "verbose_name_plural": "أنواع الشهادات الدراسية",
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "can_add_education_degree_type",
                        "يمكن اضافة اسم ونوع  الشهادة الاكاديمية",
                    ),
                    (
                        "can_update_education_degree_type",
                        "يمكن تحديث اسم ونوع الشهادة الاكاديمية  ",
                    ),
                    (
                        "can_delete_education_degree_type",
                        "يمكن حذف اسم ونوع الشهادة الاكاديمية ",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EducationDegreeTypeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "education_degree_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.educationdegreetype",
                        verbose_name="نوع الشهادة الدراسية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات نوع الشهادة الدراسية",
                "verbose_name_plural": "سجلات تغييرات أنواع الشهادات الدراسية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCourseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_number",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال   رقم كتاب اصدار الشهادة  .",
                        max_length=50,
                        null=True,
                        verbose_name="رقم كتاب اصدار الشهادة    ",
                    ),
                ),
                (
                    "date_issued",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ إصدار الشهادة.",
                        null=True,
                        verbose_name="تاريخ اصدار الشهادة",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ المباشرة بالدورة .",
                        null=True,
                        verbose_name="تاريخ المباشرة بالدورة ",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ انتهاء الدورة  .",
                        null=True,
                        verbose_name="تاريخ انتهاء الدورة  ",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="قم بتحميل ملف PDF الخاص بالشهادة الأكاديمية.",
                        null=True,
                        upload_to="coursecertificate/pdfs/",
                        verbose_name="ملف الشهادة",
                    ),
                ),
                (
                    "course_duration",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال   مدة الدورة.",
                        max_length=50,
                        null=True,
                        verbose_name="مدة الدورة   ",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات "),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="معرف فريد.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="معرف فريد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "basic_info",
                    models.ForeignKey(
                        help_text="اختر الموظف المرتبط بهذه الشهادة.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_course_certificate",
                        to="personalinfo.basicinfo",
                        verbose_name="رقم الموظف",
                    ),
                ),
                (
                    "coursecertificatetype",
                    models.ForeignKey(
                        blank=True,
                        help_text="يرجى اختيار نوع الشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_course_certificate_type",
                        to="rddepartment.coursecertificatetype",
                        verbose_name="نوع الشهادة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_course_certificate_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name_of_the_institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="يرجى اختيار المؤسسة المانحة .",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_course_certificate_institution_name",
                        to="rddepartment.coursecertificateinstitution",
                        verbose_name="اسم المؤسسة المناحة ",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة تدريبية وورش",
                "verbose_name_plural": "الشهادات التدريبية وورش العمل",
                "ordering": ["coursecertificatetype", "date_issued"],
                "permissions": [
                    ("can_add_employee_course_certificate", "يمكن إضافة شهادة تدريبية"),
                    (
                        "can_update_employee_course_certificate",
                        "يمكن تحديث شهادة تدريبية",
                    ),
                    (
                        "can_delete_employee_course_certificate",
                        "يمكن حذف شهادة تدريبية",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCourseCertificateChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "employee_course_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.employeecoursecertificate",
                        verbose_name="الشهادة التدريبية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الشهادات التدريبية",
                "verbose_name_plural": "سجلات تغييرات الشهادات التدريبية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificat_minstery_type",
                    models.CharField(
                        choices=[
                            ("education", "وزارة التربية"),
                            ("higher_education", "وزارة التعليم العالي "),
                        ],
                        help_text="اختر الوزارة المانحة للشهادة.",
                        max_length=50,
                        verbose_name="الوزارة المانحة",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True,
                        help_text="الرجاء إدخال اسم المدرسة  .",
                        max_length=255,
                        null=True,
                        verbose_name="اسم المدرسة ",
                    ),
                ),
                (
                    "university_Type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("iraqi_university", "جامعة عراقية  "),
                            ("foreign_university", "شهادة اجنبية "),
                        ],
                        default="iraqi_university",
                        help_text="يرجى اختيار نوع الجامعة اذا كاننت عراقية ام اجنبية اختياري    .",
                        max_length=50,
                        null=True,
                        verbose_name="نوع الجامعة ",
                    ),
                ),
                (
                    "Certificate_Type",
                    models.CharField(
                        blank=True,
                        help_text="يرجى ادخال التخصص الدقيق في حال الجامعات اختياري    .",
                        max_length=50,
                        null=True,
                        verbose_name="التخصص الدقيق ",
                    ),
                ),
                (
                    "date_issued",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ إصدار الشهادة.",
                        null=True,
                        verbose_name="تاريخ اصدار الشهادة",
                    ),
                ),
                (
                    "duty_assignment_number",
                    models.CharField(
                        blank=True,
                        help_text="الرجاء إدخال  رقم الامر  .",
                        max_length=255,
                        null=True,
                        verbose_name="رقم الامر ",
                    ),
                ),
                (
                    "date_of_administrative_order",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ  الامر  الخاص بالشهادة.",
                        null=True,
                        verbose_name="تاريخ  الامر",
                    ),
                ),
                (
                    "date_of_enrollment",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ المباشرة بالدراسة .",
                        null=True,
                        verbose_name="تاريخ المباشرة بالدراسة ",
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ التخرج  .",
                        null=True,
                        verbose_name="تاريخ التخرج  ",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="قم بتحميل ملف PDF الخاص بالشهادة الأكاديمية.",
                        null=True,
                        upload_to="certificates/pdfs/",
                        verbose_name="ملف الشهادة",
                    ),
                ),
                (
                    "effective_time",
                    models.DateField(
                        blank=True,
                        help_text="أدخل تاريخ  احتساب الشهادة للامور الادارية.",
                        null=True,
                        verbose_name="تاريخ تنفيذ الامر",
                    ),
                ),
                (
                    "first_approved",
                    models.BooleanField(
                        default=True,
                        help_text="تشير إلى ما اذا كان القسم المسؤول عن الدراسات قد وثق الشهادة     .",
                        verbose_name="توثيق قسم الدراسات  ",
                    ),
                ),
                (
                    "second_approved",
                    models.BooleanField(
                        default=False,
                        help_text="تشير إلى ما اذا كان القسم المسؤول عن الامور الادارية قد وثق الشهادة     .",
                        verbose_name="توثيق  الادارية  ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="معرف فريد مكون من رقم الموظف، نوع الدرجة، الكلية وتاريخ الإصدار.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="معرف فريد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "basic_info",
                    models.ForeignKey(
                        help_text="اختر الموظف المرتبط بهذه الشهادة.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_education",
                        to="personalinfo.basicinfo",
                        verbose_name="رقم الموظف",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        help_text="الكلية.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_college",
                        to="rddepartment.college",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالمدرسة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duty_assignment_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="الرجاء اختيار نوع الامر الصادر بالشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_duty_assignment_order",
                        to="hrhub.dutyassignmentorder",
                        verbose_name="نوع الامر",
                    ),
                ),
                (
                    "education_degree_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="اختر نوع الشهادة.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_education_type",
                        to="rddepartment.educationdegreetype",
                        verbose_name="نوع الشهادة",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهادة أكاديمية",
                "verbose_name_plural": "الشهادات الأكاديمية",
                "ordering": ["institution_name"],
                "permissions": [
                    ("can_add_employee_education", "يمكن إضافة  شهادة اكاديمية للموظف"),
                    (
                        "can_update_employee_education",
                        "يمكن تحديث  شهادة اكاديمية للموظيف",
                    ),
                    (
                        "can_delete_employee_education",
                        "يمكن حذف  شهادة اكاديمية للموظف",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducationChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "employee_education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.employeeeducation",
                        verbose_name="الشهادة الأكاديمية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الشهادات الأكاديمية",
                "verbose_name_plural": "سجلات تغييرات الشهادات الأكاديمية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ForeignUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        help_text="يرجى إدخال اسم الجامعة باللغة الإنجليزية.",
                        max_length=255,
                        unique=True,
                        verbose_name="اسم الجامعة الأجنبية باللغة الإنجليزية",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="يرجى إدخال اسم الجامعة باللغة العربية.",
                        max_length=255,
                        verbose_name="اسم الجامعة الأجنبية باللغة العربية",
                    ),
                ),
                (
                    "university_name_abbreviation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="يرجى إدخال مختصر اسم الجامعة باللغة الانكليزية - اختياري.",
                        max_length=10,
                        verbose_name="مختصر اسم الجامعة",
                    ),
                ),
                (
                    "university_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="يرجى ادخال رابط موقع الجامعة -اختياري - مثل  https://www.example.com",
                        max_length=255,
                        verbose_name="الرابط الإلكتروني للجامعة",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="معرف فريد للجامعة، يتم إنشاؤه تلقائيًا إذا تم تركه فارغًا.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="تاريخ ووقت إنشاء السجل.",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="تاريخ ووقت آخر تحديث للسجل.",
                        verbose_name="تاريخ التحديث",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="الرجاء اختيار اسم بلد الجامعة.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="locations.country",
                        verbose_name="بلد الجامعة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الخاصة بالجامعة الأجنبية.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="university_employment_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foreign University",
                    ),
                ),
            ],
            options={
                "verbose_name": "الجامعة الأجنبية",
                "verbose_name_plural": "الجامعات الأجنبية",
                "ordering": ["name_in_english"],
                "permissions": [
                    ("can_add_foreign_university", "يمكن إضافة   اسم جامعة اجنبية"),
                    ("can_update_foreign_university", "يمكن تحديث اسم جامعة اجنبية "),
                    ("can_delete_foreign_university", "يمكن حذف اسم جامعة اجنبية  "),
                ],
            },
        ),
        migrations.AddField(
            model_name="employeeeducation",
            name="foreign_university",
            field=models.ForeignKey(
                blank=True,
                help_text=" يرجى ادخال اسم الجامعة الاجنبية .",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_foreign_university",
                to="rddepartment.foreignuniversity",
                verbose_name=" الجامعة الاجنبية",
            ),
        ),
        migrations.CreateModel(
            name="ForeignUniversityChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "foreign_university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.foreignuniversity",
                        verbose_name="الجامعة الأجنبية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الجامعة الأجنبية",
                "verbose_name_plural": "سجلات تغييرات الجامعات الأجنبية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IraqiUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="ادخل اسم الجامعة بالعربي.",
                        max_length=255,
                        unique=True,
                        verbose_name="   اسم الجامعة باللغة العربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text=" يرجى ادخال اسم الجامعة باللغة الانكليزية.",
                        max_length=255,
                        null=True,
                        verbose_name="اسم الجامعة باللغة الانكليزية",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slug for the university, auto-generated if left blank.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "university_type",
                    models.CharField(
                        choices=[
                            ("governmental", "جامعة حكومية"),
                            ("private", "جامعة أهلية"),
                        ],
                        default="governmental",
                        help_text="يرجى اختيار هل الجامعة حكومية ام اهلية.",
                        max_length=50,
                        verbose_name="جامعة حكومية ام اهلية",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="يرجى ادخال عنوان الجامعة (اختياري).",
                        null=True,
                        verbose_name="عنوان الجامعة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموظف الذي قام بإنشاء هذه المعلومات الخاصة بالجامعة العراقية.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iraqi_university_employment_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Iraqi University ",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        help_text="     يرجى ادخال اسم المحافظة الموجودة فيها الجامعة .",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="locations.governorate",
                        verbose_name="محافطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "Iraqi University",
                "verbose_name_plural": "Iraqi Universities",
                "ordering": ["name_in_arabic"],
                "permissions": [
                    ("can_add_iraqi_university", "يمكن إضافة   اسم جامعة عراقية"),
                    ("can_update_iraqi_university", "يمكن تحديث اسم جامعة عراقية "),
                    ("can_delete_iraqi_university", "يمكن حذف اسم جامعة عراقية  "),
                ],
            },
        ),
        migrations.AddField(
            model_name="employeeeducation",
            name="iraqi_university",
            field=models.ForeignKey(
                blank=True,
                help_text=" يرجى ادخال اسم الجامعة العراقية .",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_iraqi_university",
                to="rddepartment.iraqiuniversity",
                verbose_name=" الجامعة العراقية",
            ),
        ),
        migrations.CreateModel(
            name="IraqiUniversityChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "iraqi_university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="rddepartment.iraqiuniversity",
                        verbose_name="الجامعة العراقية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الجامعة العراقية",
                "verbose_name_plural": "سجلات تغييرات الجامعات العراقية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="coursecertificateinstitution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_course_certificate_institution",
            ),
        ),
        migrations.AddConstraint(
            model_name="foreignuniversity",
            constraint=models.UniqueConstraint(
                fields=("name_in_english", "country"),
                name="unique_university_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="iraqiuniversity",
            constraint=models.UniqueConstraint(
                fields=("name_in_arabic", "governorate"),
                name="unique_iraqi_university_per_governorate",
            ),
        ),
    ]
