# Generated by Django 5.1.1 on 2025-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeerequest",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="سلاج فريد تم إنشاؤه للموظف (يتم إنشاؤه تلقائيًا).",
                max_length=100,
                unique=True,
            ),
        ),
    ]
