# Generated by Django 5.1.1 on 2025-01-17 20:08

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="يجب أن يتكون اسم المستخدم من حروف وأرقام فقط، وبطول لا يزيد عن 15 حرفًا.",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9]{1,15}$",
                                "يجب إدخال اسم مستخدم يتكون من حروف أو أرقام فقط، وبطول لا يزيد عن 15.",
                            )
                        ],
                    ),
                ),
                (
                    "is_first_login",
                    models.BooleanField(
                        default=True,
                        help_text="يتم تعيين هذه القيمة على True عندما يقوم الموظف بتسجيل الدخول لأول مرة. يتم تحديثها بعد أول تسجيل دخول.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="تحديد ما إذا كان حساب الموظف نشطًا أم لا. إذا كان غير نشط، لن يتمكن من تسجيل الدخول.",
                        verbose_name="فعال",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="يمكنك إضافة الموظف إلى واحدة أو أكثر من المجموعات. يتم استخدام المجموعات لتحديد صلاحيات الوصول والمهام.",
                        related_name="employees",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="صلاحيات محددة لهذا الموظف.",
                        to="auth.permission",
                        verbose_name="صلاحيات المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
                "permissions": [
                    ("custom_activate_employee", "يمكن تفعيل أو إلغاء تفعيل حساب موظف"),
                    (
                        "has_register_employee_permission",
                        " لديه الصلاحية بانشاء الحساب",
                    ),
                    ("custom_view_dash_board", "يمكن  مشاهدة لوحة تحكم الموظفين "),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Field Name"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Old Value"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="New Value"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Changed At"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("create", "انشاء"),
                            ("update", "تحديث"),
                            ("delete", "حذف"),
                        ],
                        max_length=50,
                        verbose_name=" نوع التغير",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حركة الحسابات",
                "verbose_name_plural": "  سجلات حركة الحسابات",
            },
        ),
        migrations.CreateModel(
            name="EmployeeActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("login", "Login"), ("logout", "Logout")],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Browser"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Operating System",
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Device"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "  سجل حركة تسجيل دخول وخروج",
                "verbose_name_plural": "   سجلات حركة تسجيل دخول وخروج",
                "indexes": [
                    models.Index(
                        fields=["employee", "timestamp"],
                        name="accounts_em_employe_667ef5_idx",
                    )
                ],
            },
        ),
    ]
