# Generated by Django 5.1.1 on 2025-01-17 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrhub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeegradestepchangelog",
            name="employee_grade_step",
        ),
        migrations.RemoveField(
            model_name="employeegradestepchangelog",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmployeeGradeStep",
        ),
        migrations.DeleteModel(
            name="EmployeeGradeStepChangeLog",
        ),
    ]
