# Generated by Django 5.1.1 on 2025-01-18 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hrhub",
            "0002_remove_employeegradestepchangelog_employee_grade_step_and_more",
        ),
        ("personalinfo", "0003_alter_basicinfo_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeGradeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_initial_employment",
                    models.BooleanField(
                        default=True,
                        help_text="حدد إذا كان هذا الموظف تعيينه هو الأول في المؤسسة حتى لا يتم احتساب السنة التجريبية لاغراض العلاوة والترفيع.",
                        verbose_name="هل هذا الموظف تعيين أولي؟",
                    ),
                ),
                (
                    "start_grade_date",
                    models.DateField(
                        blank=True,
                        help_text="التاريخ الذي بدأت فيه الدرجة الوظيفية عند التعيين.",
                        null=True,
                        verbose_name="تاريخ بداية الدرجة عند التعيين",
                    ),
                ),
                (
                    "start_step_date",
                    models.DateField(
                        blank=True,
                        help_text="التاريخ الذي بدأت فيه المرحلة الوظيفية عند التعيين.",
                        null=True,
                        verbose_name="تاريخ بداية المرحلة عند التعيين",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="ملف PDF متعلق بنوع التوظيف",
                        null=True,
                        upload_to="employement_grade_now/",
                        verbose_name="ملف PDF",
                    ),
                ),
                (
                    "auto_start_grade",
                    models.BooleanField(
                        default=True,
                        help_text="حدد فيما اذا كنت ترغب في اخذ القيمة الاولى  للمرحلة والدرجة الوظيفية عند بداية العمل بناءا على اخر  شهادة وظيفية ",
                        verbose_name="ياخذ الدرجة والمرحلة عند بدايه العمل لاخر شهادة في حال توفرها",
                    ),
                ),
                (
                    "auto_start_date",
                    models.BooleanField(
                        default=True,
                        help_text="حدد فيما اذا كنت ترغب في اخذ يوم وشهر الوظيفة الافتراضية هو تاريخ بداية احتساب الدرجة والمرحلة الوظيفية ",
                        verbose_name="اخذ تاريخ المباشرة بالعمل هو تاريخ بداية الوظيفة الافتراضية (يوم وشهر)",
                    ),
                ),
                (
                    "auto_grade_step_upgrade",
                    models.BooleanField(
                        default=True,
                        help_text="حدد ما إذا كانت الدرجة أو المرحلة الوظيفية الحالية لهذا الموظف يتم حسابها تلقائيا أم لا.",
                        verbose_name="حساب العلاوة والترفيع لهذا الموظف تلقائيا ",
                    ),
                ),
                (
                    "future_auto_grade_step_upgrade",
                    models.BooleanField(
                        default=True,
                        help_text="حدد ما إذا كانت الدرجة أو المرحلة الوظيفية القادمة لهذا الموظف يتم حسابها تلقائيا أم لا.",
                        verbose_name="حساب العلاوة والترفيع القادم لهذا الموظف تلقائيا ",
                    ),
                ),
                (
                    "current_grade_start_date",
                    models.DateField(
                        blank=True,
                        help_text="التاريخ الذي بدأت فيه الدرجة الوظيفية الحالية.",
                        null=True,
                        verbose_name="تاريخ بداية الدرجة الحالية",
                    ),
                ),
                (
                    "total_step_grade_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سنة تجريبية "
                    ),
                ),
                (
                    "total_step_grade_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="اشهر السنة التجريبية "
                    ),
                ),
                (
                    "total_step_grade_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ايام السنة التجريبية "
                    ),
                ),
                (
                    "division_rate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="سنوات التحول الى الدرجة الاخرى - في حال كانت فارغة فانها ياخذ القيمة المثبتة باخر شهادة للموظف وفي حال لم يكن للموظف اخر شهادة فان النظام كل 4 سنوات ويحول الدرجة",
                        null=True,
                        verbose_name="سنوات الترقية  ",
                    ),
                ),
                (
                    "stop_grade",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text=" درجة التوقف وفي حال تركه فارغا يتم اخذ قيمته من اخر شهادة وفي حال لم يكن متوفر في الشهادة والحقل فارغا فان القيمة تكون 1",
                        null=True,
                        verbose_name=" درجة التوقف  ",
                    ),
                ),
                (
                    "total_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="السنوات الإجمالية"
                    ),
                ),
                (
                    "total_months",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الشهور الإجمالية"
                    ),
                ),
                (
                    "total_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الأيام الإجمالية"
                    ),
                ),
                (
                    "current_deserving",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="المدة المتبقية او المدة الفائتة للاستحقاق الحالي   ",
                    ),
                ),
                (
                    "next_deserving",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="المدة المتبقية للاستحقاق المستقبلي ",
                    ),
                ),
                (
                    "future_effective_date",
                    models.DateField(
                        blank=True,
                        help_text="التاريخ المتوقع لتفعيل الدرجة أو المرحلة الوظيفية القادمة.",
                        null=True,
                        verbose_name="تاريخ سريان الدرجة/المرحلة القادمة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "موافقة"),
                            ("deserving", "مستحق"),
                            ("pending", "انتظار"),
                            ("rejected", "رفض"),
                        ],
                        default="pending",
                        help_text="الحالة الحالية للسجل",
                        max_length=10,
                        null=True,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="حدد ما إذا كانت الدرجة أو المرحلة الوظيفية الحالية نشطة أم لا.",
                        verbose_name="هل السجل نشط؟",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        help_text="ملاحظات",
                        max_length=255,
                        null=True,
                        verbose_name="ملاحظات ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="الطابع الزمني عند إنشاء البيانات.",
                        verbose_name="تاريخ الإنشاء",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="الطابع الزمني عند آخر تحديث للبيانات.",
                        verbose_name="آخر تحديث",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "basic_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_grade_step",
                        to="personalinfo.basicinfo",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموظف الذي أنشأ أو وافق على ادخال البيانات.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_create_grade_step",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "future_grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="الدرجة الوظيفية التي سيتم الانتقال إليها",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_grade_employee_grade_step",
                        to="hrhub.employeegrade",
                        verbose_name="الدرجة الوظيفية القادمة",
                    ),
                ),
                (
                    "future_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="المرحلة الوظيفية التي سيتم الانتقال إليها",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="future_step_employee_step_levels",
                        to="hrhub.employeestep",
                        verbose_name="المرحلة الوظيفية القادمة",
                    ),
                ),
                (
                    "grade_now",
                    models.ForeignKey(
                        blank=True,
                        help_text="الدرجة الوظيفية الموظف الان  ",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="now_grade_employee_grade_step",
                        to="hrhub.employeegrade",
                        verbose_name="الدرجة الوظيفية الان   ",
                    ),
                ),
                (
                    "grade_temp",
                    models.ForeignKey(
                        blank=True,
                        help_text="الدرجة الوظيفية الموظف مؤقتا  ",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_grade_employee_grade_step",
                        to="hrhub.employeegrade",
                        verbose_name="الدرجة الوظيفية مؤقتا   ",
                    ),
                ),
                (
                    "start_grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="الدرجة الوظيفية الموظف عند بدء العمل",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_grade_employee_grade_step",
                        to="hrhub.employeegrade",
                        verbose_name="الدرجة الوظيفية عند بداية التعين ",
                    ),
                ),
                (
                    "start_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="المرحلة الوظيفية للموظف عند بدء العمل",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_step_employee_step_levels",
                        to="hrhub.employeestep",
                        verbose_name="المرحلة الوظيفية عند بداية التعين ",
                    ),
                ),
                (
                    "step_now",
                    models.ForeignKey(
                        blank=True,
                        help_text="المرحلة الوظيفية للموظف   الان",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="now_step_employee_step_levels",
                        to="hrhub.employeestep",
                        verbose_name="المرحلة الوظيفية   الان ",
                    ),
                ),
                (
                    "step_temp",
                    models.ForeignKey(
                        blank=True,
                        help_text="المرحلة الوظيفية للموظف   مؤقتا",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_step_employee_step_levels",
                        to="hrhub.employeestep",
                        verbose_name="المرحلة الوظيفية   موقتا ",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل الموظف الوظيفي من حيث الدرجة والمرحلة ",
                "verbose_name_plural": "سجلات الموظف الوظيفي من حيث الدرجة والمرحلة ",
                "permissions": [
                    (
                        "can_add_employee_grade_step",
                        "يمكنه اضافة ترفيعات وعلاوات        ",
                    ),
                    (
                        "can_update_employee_grade_step",
                        "يمكنه تحديث ترفيعات و علاوات الموظف        ",
                    ),
                    (
                        "can_delete_employee_grade_step",
                        "يمكنه حذف ترفيعات و علاوات الموظف        ",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeGradeStepChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        help_text="العملية التي تمت على السجل.",
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم الحقل الذي تم تغييره.",
                        max_length=100,
                        null=True,
                        verbose_name="اسم الحقل",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        help_text="القيمة القديمة للحقل.",
                        null=True,
                        verbose_name="القيمة القديمة",
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True,
                        help_text="القيمة الجديدة للحقل.",
                        null=True,
                        verbose_name="القيمة الجديدة",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="الوقت الذي تم فيه التغيير.",
                        verbose_name="وقت التغيير",
                    ),
                ),
                (
                    "employee_grade_step",
                    models.ForeignKey(
                        blank=True,
                        help_text="السجل المرتبط بالتغيير.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="hrhub.employeegradestep",
                        verbose_name="سجل درجة ومرحلة الموظف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بالتغيير.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات درجة ومرحلة الموظف",
                "verbose_name_plural": "سجلات تغييرات درجة ومرحلة الموظف",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="employeegradestep",
            constraint=models.UniqueConstraint(
                fields=("basic_info",), name="unique_employee_grade_step"
            ),
        ),
    ]
