# Generated by Django 5.1.1 on 2025-01-17 20:08

import django.core.validators
import django.db.models.deletion
import personalinfo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("A-", "A-"),
                            ("B-", "B-"),
                            ("AB-", "AB-"),
                            ("O-", "O-"),
                        ],
                        help_text="فصيلة دم الموظف.",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "أعزب"),
                            ("married", "متزوج"),
                            ("divorced", "مطلق"),
                            ("widowed", "أرمل"),
                        ],
                        help_text="الحالة الاجتماعية للموظف.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="عنوان الموظف.", null=True),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="اسم الشخص للطوارئ.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم هاتف الطوارئ.",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الطوارئ 11 رقمًا.",
                                regex="^\\d{11}$",
                            )
                        ],
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للموظف.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="تشير إلى ما إذا كانت المعلومات الإضافية معتمدة.",
                        verbose_name="معلومات إضافية معتمدة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء أو تحديث هذه المعلومات.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_infos_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "governorate_of_residence",
                    models.ForeignKey(
                        blank=True,
                        help_text="المحافظة التي يسكن فيها الموظف    ",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_infos",
                        to="locations.governorate",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات اضافية",
                "verbose_name_plural": "معلومات اضافية",
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "can_add_employee_additional_info",
                        "يمكنه اضافة بيانات  اضافية للموظف       ",
                    ),
                    (
                        "can_view_employee_additional_info",
                        "يمكنه عرض البيانات  الاضافية للموظف       ",
                    ),
                    (
                        "can_update_employee_additional_info",
                        "يمكنه تحديث البيانات  الاضافية للموظف       ",
                    ),
                    (
                        "can_delete_employee_additional_info",
                        "يمكنه حذف البيانات  الاضافية للموظف       ",
                    ),
                    ("can_update_blood_type", "يمكن تحديث فصيلة الدم"),
                    ("can_update_religion", "يمكن تحديث الديانة"),
                    ("can_update_nationalism", "يمكن تحديث القومية"),
                    ("can_update_marital_status", "يمكن تحديث الحالة الاجتماعية"),
                    ("can_update_governorate_of_residence", "يمكن تحديث مكان الإقامة"),
                    ("can_update_address", "يمكن تحديث العنوان"),
                    ("can_update_emergency_contact", "يمكن تحديث بيانات الطوارئ"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdditionalInfoChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "additional_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.additionalinfo",
                        verbose_name="معلومات إضافية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات المعلومات الإضافية",
                "verbose_name_plural": "سجلات تغييرات المعلومات الإضافية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        help_text="الاسم الأول للموظف.",
                        max_length=50,
                        verbose_name="الاسم الاول ",
                    ),
                ),
                (
                    "secondname",
                    models.CharField(
                        help_text="الاسم الثاني للموظف.",
                        max_length=50,
                        verbose_name="الاسم الثاني ",
                    ),
                ),
                (
                    "thirdname",
                    models.CharField(
                        help_text="الاسم الثالث للموظف.",
                        max_length=50,
                        verbose_name="الاسم الثالث ",
                    ),
                ),
                (
                    "fourthname",
                    models.CharField(
                        blank=True,
                        help_text="الاسم الرابع للموظف.",
                        max_length=50,
                        null=True,
                        verbose_name="الاسم الرابع ",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True,
                        help_text="لقب الموظف.",
                        max_length=50,
                        null=True,
                        verbose_name="اللقب  ",
                    ),
                ),
                (
                    "mothername",
                    models.CharField(
                        blank=True,
                        help_text="اسم والدة الموظف.",
                        max_length=50,
                        null=True,
                        verbose_name="اسم الوالدة  ",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="مطلوب. 11 رقماً فقط.",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="يجب أن يكون رقم الهاتف 11 رقماً فقط.",
                                regex="^\\d{11}$",
                            )
                        ],
                        verbose_name="رقم الهاتف  ",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="عنوان البريد الإلكتروني الفريد للموظف.",
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="أدخل عنوان بريد إلكتروني صحيح."
                            )
                        ],
                        verbose_name="البريد الالكتروني  ",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="تاريخ ميلاد الموظف (اختياري).",
                        null=True,
                        verbose_name="تاريخ الميلاد  ",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "ذكر"), ("F", "أنثى")],
                        help_text="جنس الموظف.",
                        max_length=1,
                        null=True,
                        verbose_name="جنس الموظف  ",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="سيرة قصيرة للموظف (اختياري).", null=True
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="صورة ملف تعريف الموظف (اختياري).",
                        null=True,
                        upload_to=personalinfo.models.user_avatar_path,
                        verbose_name="صورة شخصية  ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للموظف (يتم إنشاؤه تلقائيًا).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="تشير إلى ما إذا كانت المعلومات الأساسية معتمدة.",
                        verbose_name="معلومات أساسية معتمدة",
                    ),
                ),
                (
                    "emplpyee_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عمر الموظف  "
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات الأساسية.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_basic_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emp_id",
                    models.OneToOneField(
                        help_text="الموظف المرتبط بهذه المعلومات الأساسية.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place_of_birth",
                    models.ForeignKey(
                        blank=True,
                        help_text="المحافظة التي وُلد فيها الموظف.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="basicinfo_place_of_birth",
                        to="locations.governorate",
                        verbose_name=" محل الميلاد ",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات أساسية",
                "verbose_name_plural": "معلومات أساسية",
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "can_access_employee_dashboard",
                        "يمكنه الوصول الى لوحة تحكم الموظفين   ",
                    ),
                    (
                        "can_add_employee_basic_info",
                        "يمكنه اضافة بيانات  اساسية للموظف       ",
                    ),
                    (
                        "can_view_employee_basic_info",
                        "يمكنه عرض بيانات  اساسية للموظف       ",
                    ),
                    (
                        "can_update_employee_basic_info",
                        "يمكنه تحديث البيانات  الاساسية للموظف       ",
                    ),
                    (
                        "can_delete_employee_basic_info",
                        "يمكنه حذف البيانات  الاساسية للموظف       ",
                    ),
                    ("can_update_firstname", "يمكن تحديث الاسم الأول"),
                    ("can_update_secondname", "يمكن تحديث الاسم الثاني"),
                    ("can_update_thirdname", "يمكن تحديث الاسم الثالث"),
                    ("can_update_fourthname", "يمكن تحديث الاسم الرابع"),
                    ("can_update_surname", "يمكن تحديث اللقب"),
                    ("can_update_mothername", "يمكن تحديث اسم الأم"),
                    ("can_update_phonenumber", "يمكن تحديث رقم الهاتف"),
                    ("can_update_email", "يمكن تحديث البريد الإلكتروني"),
                    ("can_update_date_of_birth", "يمكن تحديث تاريخ الميلاد"),
                    ("can_update_place_of_birth", "يمكن تحديث مكان الميلاد"),
                    ("can_update_gender", "يمكن تحديث الجنس"),
                    ("can_update_bio", "يمكن تحديث السيرة الذاتية"),
                    ("can_update_avatar", "يمكن تحديث الصورة الشخصية"),
                ],
            },
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="basic_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to="personalinfo.basicinfo",
            ),
        ),
        migrations.CreateModel(
            name="BasicInfoChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "basic_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.basicinfo",
                        verbose_name="معلومات أساسية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات المعلومات الأساسية",
                "verbose_name_plural": "سجلات تغييرات المعلومات الأساسية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Nationalism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم القومية بالعربية.",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم القومية بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم القومية بالانكليزية.",
                        max_length=100,
                        null=True,
                        verbose_name="اسم القومية  بالانكليزية",
                    ),
                ),
                (
                    "commennts",
                    models.CharField(
                        blank=True,
                        help_text="ملاحظات عن الوثيقة   ",
                        max_length=250,
                        null=True,
                        verbose_name="ملاحظات عن  الوثيقة  ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للقومية (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموظف الذي قام بإنشاء هذه المعلومات الخاصة بالقومية.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nationalism_employment_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="موظف القومية",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات القوميات",
                "verbose_name_plural": "معلومات القومية",
                "ordering": ["created_at"],
                "permissions": [
                    ("can_create_nationalism", "اضافة قومية"),
                    ("can_update_nationalism", "تحديث القومية"),
                    ("can_delete_nationalism", "حذف القومية"),
                ],
            },
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="nationalism",
            field=models.ForeignKey(
                blank=True,
                help_text="اختر قومية الموظف.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employeenationalism",
                to="personalinfo.nationalism",
                verbose_name="nationalism",
            ),
        ),
        migrations.CreateModel(
            name="NationalismChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "nationalism",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.nationalism",
                        verbose_name="معلومات القومية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات القومية",
                "verbose_name_plural": "سجلات تغييرات القومية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Official_Documents_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم الوثيقة بالعربية.",
                        max_length=100,
                        unique=True,
                        verbose_name="اسم الوثيقة  بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم الوثيقة بالانكليزية.",
                        max_length=100,
                        null=True,
                        verbose_name="اسم الوثيقة  بالانكليزية",
                    ),
                ),
                (
                    "commennts",
                    models.CharField(
                        blank=True,
                        help_text="ملاحظات عن الوثيقة   ",
                        max_length=250,
                        null=True,
                        verbose_name="ملاحظات عن  الوثيقة  ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للاسم الشهادة (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات  .",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_documents_type_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع الوثيقة الرسمية  ",
                "verbose_name_plural": "انواع  الوثائق الرسمية ",
                "ordering": ["created_at"],
                "permissions": [
                    ("can_create_official_documents_type", "اضافة نوع وثيقة رسمية "),
                    ("can_update_official_documents_type", "تحديث الوثيقة الرسمية"),
                    ("can_delete_official_documents_type", "حذف الوثيقة الرسمية"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficialDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_documents_id_number",
                    models.CharField(
                        blank=True,
                        help_text="رقم الوثيقة  الرسمية.",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name=" رقم الوثيقة",
                    ),
                ),
                (
                    "personal_id_issuance_date",
                    models.DateField(
                        blank=True,
                        help_text="تاريخ صدور الوثيقة  (اختياري).",
                        null=True,
                        verbose_name=" تاريخ صدور الوثيقة   ",
                    ),
                ),
                (
                    "personal_id_expire_date",
                    models.DateField(
                        blank=True,
                        help_text="تاريخ انتهاء الوثيقة  (اختياري).",
                        null=True,
                        verbose_name=" تاريخ انتهاء  الوثيقة ",
                    ),
                ),
                (
                    "personal_id_front_page",
                    models.ImageField(
                        blank=True,
                        help_text="الواجهة الامامية للبطاقة الوطنية للموظف",
                        null=True,
                        upload_to=personalinfo.models.user_personal_id_path,
                        verbose_name=" الصفحة الامامية للوثيقة   ",
                    ),
                ),
                (
                    "personal_id_back_page",
                    models.ImageField(
                        blank=True,
                        help_text="الواجهة الخلفية للبطاقة الوطنية للموظف",
                        null=True,
                        upload_to=personalinfo.models.user_personal_id_path,
                        verbose_name=" الصفحة الخلفية للوثيقة   ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للاسم الشهادة (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "basic_info",
                    models.ForeignKey(
                        help_text="اختر الموظف المرتبط بهذه الوئيقة.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_official_documents",
                        to="personalinfo.basicinfo",
                        verbose_name="رقم الموظف",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="المستخدم الذي قام بإنشاء هذه المعلومات  .",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_documents_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        help_text="المحافظة التي تم اصدار الوثيقة منها-اختياري .",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_documents_id_issuer",
                        to="locations.governorate",
                        verbose_name=" جهة اصدار الوثيقة ",
                    ),
                ),
                (
                    "official_documents_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="    يرجى اختيار نوع الوثيقة الرسمية  مثل بطاقة وطنية او غيرها    .",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_documents_type",
                        to="personalinfo.official_documents_type",
                        verbose_name="نوع الوثيقة",
                    ),
                ),
            ],
            options={
                "verbose_name": " الوثيقة الرسمية ",
                "verbose_name_plural": "  الوثائق الرسمية ",
                "ordering": ["created_at"],
                "permissions": [
                    ("can_view_official_documents", "عرض  وثيقة رسمية للموظف "),
                    ("can_create_official_documents", "اضافة  وثيقة رسمية للموظف "),
                    ("can_update_official_documents", "تحديث الوثيقة الرسمية للموظف"),
                    ("can_delete_official_documents", "حذف الوثيقة الرسمية للموظف"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficialDocumentsChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "official_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.officialdocuments",
                        verbose_name="الوثيقة الرسمية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الوثيقة الرسمية",
                "verbose_name_plural": "سجلات تغييرات الوثائق الرسمية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OfficialDocumentsTypeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "official_document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.official_documents_type",
                        verbose_name="نوع الوثيقة الرسمية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات نوع الوثيقة الرسمية",
                "verbose_name_plural": "سجلات تغييرات أنواع الوثائق الرسمية",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_in_arabic",
                    models.CharField(
                        help_text="يرجى إدخال اسم الديانة بالعربية.",
                        max_length=50,
                        unique=True,
                        verbose_name="اسم الديانة بالعربية",
                    ),
                ),
                (
                    "name_in_english",
                    models.CharField(
                        blank=True,
                        help_text="يرجى إدخال اسم الديانة بالانكليزية.",
                        max_length=100,
                        null=True,
                        verbose_name="اسم  الديانة بالانكليزية",
                    ),
                ),
                (
                    "commennts",
                    models.CharField(
                        blank=True,
                        help_text="ملاحظات عن الديانة   ",
                        max_length=250,
                        null=True,
                        verbose_name="ملاحظات عن  الديانة  ",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="سلاج فريد تم إنشاؤه للموظف (يتم إنشاؤه تلقائيًا).",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="التوقيت الذي تم فيه إنشاء السجل."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="التوقيت الذي تم فيه تحديث السجل آخر مرة.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="الموظف الذي قام بإنشاء هذه المعلومات الخاصة بالديانة.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="religion_employment_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="موظف الديانة",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات الديانات",
                "verbose_name_plural": "معلومات الديانة",
                "ordering": ["created_at"],
                "permissions": [
                    ("can_create_religion", "اضافة ديانة"),
                    ("can_update_religion", "تحديث الديانة"),
                    ("can_delete_religion", "حذف الديانة"),
                ],
            },
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="religion",
            field=models.ForeignKey(
                blank=True,
                help_text="اختر ديانة الموظف.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employeereligion",
                to="personalinfo.religion",
                verbose_name="religion",
            ),
        ),
        migrations.CreateModel(
            name="ReligionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="personalinfo.religion",
                        verbose_name="معلومات الديانة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الديانة",
                "verbose_name_plural": "سجلات تغييرات الديانة",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="basicinfo",
            index=models.Index(
                fields=["emp_id"], name="personalinf_emp_id__80f46f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basicinfo",
            index=models.Index(
                fields=["phone_number"], name="personalinf_phone_n_f3ef08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialdocuments",
            constraint=models.UniqueConstraint(
                fields=("basic_info", "official_documents_type"),
                name="unique_employee_document_type",
            ),
        ),
    ]
