# Generated by Django 5.1.1 on 2025-01-18 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personalinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basicinfo",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    (
                        "can_access_employee_dashboard",
                        "يمكنه الوصول الى لوحة تحكم الموظفين   ",
                    ),
                    (
                        "can_add_employee_basic_info",
                        "يمكنه اضافة بيانات  اساسية للموظف       ",
                    ),
                    (
                        "can_view_employee_basic_info",
                        "يمكنه عرض بيانات  اساسية للموظف       ",
                    ),
                    (
                        "can_update_employee_basic_info",
                        "يمكنه تحديث البيانات  الاساسية للموظف       ",
                    ),
                    (
                        "can_delete_employee_basic_info",
                        "يمكنه حذف البيانات  الاساسية للموظف       ",
                    ),
                    ("can_update_firstname", "يمكن تحديث الاسم الأول"),
                    ("can_update_secondname", "يمكن تحديث الاسم الثاني"),
                    ("can_update_thirdname", "يمكن تحديث الاسم الثالث"),
                    ("can_update_fourthname", "يمكن تحديث الاسم الرابع"),
                    ("can_update_surname", "يمكن تحديث اللقب"),
                    ("can_update_mothername", "يمكن تحديث اسم الأم"),
                    ("can_update_phonenumber", "يمكن تحديث رقم الهاتف"),
                    ("can_update_email", "يمكن تحديث البريد الإلكتروني"),
                    ("can_update_date_of_birth", "يمكن تحديث تاريخ الميلاد"),
                    ("can_update_place_of_birth", "يمكن تحديث مكان الميلاد"),
                    ("can_update_gender", "يمكن تحديث الجنس"),
                    ("can_update_bio", "يمكن تحديث السيرة الذاتية"),
                    ("can_update_avatar", "يمكن تحديث الصورة الشخصية"),
                    (
                        "can_quick_search",
                        "لديه  القدرة على الوصول الى ايقونه البحث السريع   ",
                    ),
                ],
                "verbose_name": "معلومات أساسية",
                "verbose_name_plural": "معلومات أساسية",
            },
        ),
    ]
