# Generated by Django 5.1.1 on 2025-01-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تم الإنشاء في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تم التحديث في"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="الـ slug يتم إنشاؤه تلقائيًا من الاسم إذا لم يتم توفيره",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="الـ slug",
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="القارة بالإنجليزية"
                    ),
                ),
                (
                    "name_arabic",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="القارة بالعربية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "القارة",
                "verbose_name_plural": "القارات",
                "ordering": ["name_english"],
                "permissions": [
                    ("can_view_continent", "عرض تفاصيل القارات"),
                    ("can_create_continent", " القدرة على اضافة  قارة"),
                    ("can_update_continent", " القدرة على تحديث القارات"),
                    ("can_delete_continent", "القدرة على حذف  القارات"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContinentChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "continent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="locations.continent",
                        verbose_name="معلومات القارة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات القارة",
                "verbose_name_plural": "سجلات تغييرات القارات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تم الإنشاء في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تم التحديث في"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="الـ slug يتم إنشاؤه تلقائيًا من الاسم إذا لم يتم توفيره",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="الـ slug",
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="الدولة بالإنجليزية"
                    ),
                ),
                (
                    "name_arabic",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="الدولة بالعربية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.continent",
                        verbose_name="القارة",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "الدولة",
                "verbose_name_plural": "الدول",
                "ordering": ["name_english"],
                "permissions": [
                    ("can_view_country_details", "عرض تفاصيل الدول"),
                    ("can_create_country", "اضافة دول"),
                    ("can_update_country", "تحديث الدول"),
                    ("can_delete_country", "حذف الدول"),
                ],
                "unique_together": {("name_english", "name_arabic")},
            },
        ),
        migrations.CreateModel(
            name="CountryChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="locations.country",
                        verbose_name="معلومات الدولة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات الدولة",
                "verbose_name_plural": "سجلات تغييرات الدول",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تم الإنشاء في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تم التحديث في"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="الـ slug يتم إنشاؤه تلقائيًا من الاسم إذا لم يتم توفيره",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="الـ slug",
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="المحافظة بالإنجليزية",
                    ),
                ),
                (
                    "name_arabic",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المحافظة بالعربية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "المحافظة",
                "verbose_name_plural": "المحافظات",
                "permissions": [
                    ("can_view_governorate_details", "عرض تفاصيل المحافظة"),
                    ("can_reate_governorate", "اضافة المحافظة"),
                    ("can_update_governorate", "تحديث المحافظة"),
                    ("can_delete_governorate", "حذف المحافظة"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GovernorateChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="locations.governorate",
                        verbose_name="معلومات المحافظة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات المحافظة",
                "verbose_name_plural": "سجلات تغييرات المحافظات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تم الإنشاء في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تم التحديث في"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="الـ slug يتم إنشاؤه تلقائيًا من الاسم إذا لم يتم توفيره",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="الـ slug",
                    ),
                ),
                (
                    "name_english",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الاسم بالإنجليزية",
                    ),
                ),
                (
                    "name_arabic",
                    models.CharField(max_length=100, verbose_name="الاسم بالعربية"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.governorate",
                        verbose_name="المحافظة",
                    ),
                ),
            ],
            options={
                "verbose_name": "المنطقة",
                "verbose_name_plural": "المناطق",
                "permissions": [
                    ("can_view_region_details", "عرض تفاصيل المناطق"),
                    ("can_create_region", "اضافة منطقة"),
                    ("can_update_region", "تحديث منطقة"),
                    ("can_delete_region", "حذف منطقة"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "إضافة"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                        verbose_name="نوع العملية",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="اسم الحقل"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة القديمة"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="القيمة الجديدة"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التغيير"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="locations.region",
                        verbose_name="معلومات المنطقة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تغييرات المنطقة",
                "verbose_name_plural": "سجلات تغييرات المناطق",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("governorate", "name_english"),
                name="unique_region_per_governorate",
            ),
        ),
    ]
