# Generated by Django 5.1.1 on 2025-01-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="continent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.continent",
                verbose_name="القارة",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="الوصف"),
        ),
    ]
