# Generated by Django 5.1.1 on 2025-01-18 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_alter_country_name_english"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name_arabic",)},
        ),
    ]
